name: Deploy Backend API

on:
  push:
    branches:
      - dev
      - main
    paths:
      - backend-api/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: backend-api

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Backend API
        uses: azure/webapps-deploy@v2
        with:
          app-name: backend-api-joedevopslab
          package: ./backend-api
